spring.application.name=SafeRoad iRAD
server.port=8080

# Thymeleaf settings
spring.thymeleaf.cache=false
spring.thymeleaf.suffix=.html

# Disable default Spring Security password generation
logging.level.org.springframework.security=WARN
